# This is a basic workflow to help you get started with Actions

name: Run Arxiv Papers Daily

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron:  "0 0/12 * * *"  #'*/60 * * * *'
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches:
#     - main

env:

  GITHUB_USER_NAME: nickdee96
  GITHUB_USER_EMAIL: mumeronick@gmail.com


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: update
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Set up Python Env
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          #architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run daily arxiv 
        run: |
          ls .
          ls ..
          python daily_arxiv.py
          
      - name: Push new cv-arxiv-daily.md
        run: |
          git config --local user.email "${{ env.GITHUB_USER_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_USER_NAME }}"
          git add README.md docs/asr-arxiv-daily.json docs/asr-arxiv-daily-web.json docs/index.md docs/asr-arxiv-daily-wechat.json
          git diff --staged --quiet || git commit -m "Github Action Automatic Update ASR Arxiv Papers"
          git push
